mod.group = "ct.buildcraft.ce"
mod.id = "buildcraft"
mod.name = "BuildCraft Community Edition"
mod.version = "8.0.13"
mod.archive_name = "BuildCraft-Community-Edition"
mod.authors = "CurativeTree, ShipovskijKorp"
mod.license = "MPL-2.0"

deps.junit = "5.9.3"

[forge."1.19.2"]
deps.minecraft = "1.19.2"
deps.forge = "43.5.0"
java.version = "17"

loader.version_range = "[43,)"
forge.version_range = "[43.2.0,)"
minecraft.version_range = "[1.19.2,1.20)"
buildcraft.version_range = "[8.0.0.0,)"

pack.format = "9"
pack.resource_format = "9"
pack.data_format = "10"
network.protocol = "BC8.0.x-1.19.2-net2"

compat.jei.range = "[11,)"
compat.jade.range = "[8,)"
compat.ic2.range = "[1.19.2-2.1.2.1,)"
compat.forestry.range = "[1.0.0,)"

deps.jei = "maven.modrinth:u6dRKJwZ:qMHEoNl6"
deps.jade = "maven.modrinth:nvQzSEkH:kp0HjPre"
deps.ic2 = "maven.modrinth:nIaMQHTd:2.1.3.3"
deps.carbon_config = "maven.modrinth:1jDdpgcc:8U1HA7TK"
deps.forestry = "maven.modrinth:2oORTOi2:q98RKZEA"
deps.patchouli = "maven.modrinth:patchouli:62ztr7HA"

[forge."1.20.1"]
source.root = "version-src/1.20.1-forge"

deps.minecraft = "1.20.1"
deps.forge = "47.4.10"
java.version = "17"

loader.version_range = "[47,)"
forge.version_range = "[47.4.10,)"
minecraft.version_range = "[1.20.1,1.20.2)"
buildcraft.version_range = "[8.0.0.0,)"

pack.format = "15"
pack.resource_format = "15"
pack.data_format = "15"
network.protocol = "BC8.0.x-1.20.1-net2"

compat.jei.range = "[15,)"
compat.jade.range = "[11,)"
compat.ic2.range = "[0,)"
compat.ic2.enabled = false
compat.forestry.range = "[2.10.2,)"

deps.jei = "maven.modrinth:jei:MybRLD9h"
deps.jade = "maven.modrinth:jade:dldgfOqB"
deps.ic2 = ""
deps.carbon_config = ""
deps.forestry = "maven.modrinth:2oORTOi2:IAIRb23N"
deps.patchouli = "maven.modrinth:nU0bVIaL:94dtOLgZ"
