modLoader="lowcodefml"
loaderVersion="[47,)"
license="MPL-2.0"
showAsResourcePack=false
clientSideOnly=true

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    authors="CurativeTree, ShipovskijKorp"
    credits="Special thanks to the original BuildCraft team and all localization contributors."
    description='''
Additional interface and Guide Book translations for BuildCraft Community Edition.
English remains bundled with the main BuildCraft mod and is used as the fallback language.
    '''
    displayTest="IGNORE_ALL_VERSION"

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="[47.1.0,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.${mod_id}]]
    modId="buildcraftlib"
    mandatory=true
    versionRange="[8.0.0.0,)"
    ordering="AFTER"
    side="CLIENT"
